### ISSUE TITLE
Multiple master problem

### ISSUE THREAD

**Issue by margaretdax** [awslabs/eb-locustio-sample#2]
Experiencing an issue where multiple EC2 instances believe they are the master. Napkin math tells us that a load test using 3 instances will require each instance to attempt to become the master less than 6 seconds within each other (time - (3 instances) \* 2).to_i. I believe I've experienced many issues scaling beyond one instance because of this timeout. Once I removed the timeout I haven't had issues with multiple master nodes spawning.

I was going to add the app version to the hash key, but it seems getting the app name or version from within the running app is a relatively unsolved problem for Elastic Beanstalk. I noticed that when getting the number of instances the environment is queried directly. It's possible I'm misunderstanding but I'd think this would be a faulty number to use when there are multiple apps running in an environment.

**Comment by larssn** [comment]
I believe I ran into this issue as well. Not sure how it happened: First day it worked fine, but after subsequently updating the parameters as per the guide at https://blogs.aws.amazon.com/application-management/post/Tx351HCZ9D1RQ84/Using-Locust-on-AWS-Elastic-Beanstalk-for-Distributed-Load-Generation-and-Testin
 it started behaving strangely.

**Comment by abhiksingh** [comment]
Apologies for the late response. For some reason I wasn't receiving notifications for issues on this repo.

@mollrow using the app ID in EB would be the best approach to solve the problem of a unique key per deployment. I chose to use the timeout because the ID or app name isn't easily accessible from within the EB environment. The timeout is really there to ensure that all instances don't attempt to become master at the same time.

I'm going to look into fixing this in the near future.

**Comment by abhiksingh** [comment]
@mollrow The latest commit should fix this issue. Please feel free to re-open the issue if it doesn't.
